language: clojure

lein: lein2

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

after_success:
  - CLOVERAGE_VERSION=1.0.6 lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json